[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
name = "test-target"
publish = false
edition = "2021"
version = "0.1.0"
resolver = "2"

[[test]]
name = "test"
harness = false

[[test]]
name = "imu_ism330dhcx"
harness = false

[[test]]
name = "gps"
harness = false

[[test]]
name = "storage"
harness = false

[[test]]
name = "sd_direct"
harness = false

[[test]]
name = "cellular"
harness = false

[[test]]
name = "cellular_sensor_data"
harness = false

[[test]]
name = "temp_sensor"
harness = false

[[test]]
name = "blink"
harness = false

[dependencies]
sfy = { path = "../", default-features = false, features = [ "target-test" ] }
heapless = { version = "0.7", features = [ "serde", "ufmt-impl", "defmt-impl" ] }
serde = { version = "1", features = ["derive"], default-features = false }
serde-json-core = "0.4.0"
cortex-m = { version = "*", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7"
defmt = "0.3"
defmt-rtt = "0.4"
defmt-test = "*"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
ism330dhcx = "0.5.1"
chrono = { version = "0.4.19", default-features = false }
embedded-hal = "0.2.6"
cmsis_dsp = { version = "0.1.0", features = [ "micromath" ] }
embedded-sdmmc = { version = "0.6.0", default-features = false, features = ["defmt-log"] }
micromath = "2.1.0"
one-wire-bus = "*"

[dependencies.ambiq-hal]
version = "0.3"
features = ["ambiq-sdk", "sparkfun-redboard-nano", "rt"]
git = "https://github.com/gauteh/ambiq-rs"

