[package]
name = "sfy"
version = "0.1.0"
edition = "2021"
default-run = "sfy"

[workspace]
members = [ "target-test" ]

[dependencies]
heapless = { version = "0.7", features = [ "serde", "ufmt-impl", "defmt-impl" ] }
serde = { version = "1", features = ["derive"], default-features = false }
serde-json-core = "0.4.0"
cortex-m = "*"
cortex-m-rt = "0.7.0"
ufmt = "0.1.0"
nb = "1.0.0"
embedded-hal = "0.2.6"
defmt = "0.3"
defmt-rtt = "0.3"
# panic-probe = { version = "0.3.0", features = ["print-defmt"] }
ism330dhcx = "0.4.0"
cmsis_dsp = { version = "0.1.0", features = [ "micromath" ] }
micromath = { version = "2", features = [ "quaternion", "vector" ] }
bytemuck = "1.7.2"
base64 = { version = "0.13.0", default-features = false }
shared-bus = { version = "0.2.2", features = [ "cortex-m" ] }
half = { version = "1.8.2", features = [ "use-intrinsics", "bytemuck", "serde" ] }
chrono = { version = "0.4.19", default-features = false }
embedded-sdmmc = { version = "0.3.0", default-features = false, features = ["defmt-log"], optional = true }
git-version = "0.3.5"
postcard = { version = "0.7.3", optional = true }
static_assertions = "1.1.0"

[dependencies.notecard]
git = "https://github.com/gauteh/notecard-rs"

[dependencies.ambiq-hal]
version = "0.2"
features = ["ambiq-sdk", "sparkfun-redboard-nano", "rt"]
git = "https://github.com/gauteh/ambiq-rs"

[dependencies.ahrs-fusion]
git = "https://github.com/gauteh/ahrs-fusion"

[dev-dependencies]

[patch.crates-io]
# ism330dhcx = { git = "https://github.com/gauteh/ism330dhcx", branch = "fifo" }
cmsis_dsp = { git = "https://github.com/samcrow/cmsis_dsp.rs" }
embedded-sdmmc = { git = "https://github.com/gauteh/embedded-sdmmc-rs", branch = "more-defmt" }
# embedded-sdmmc = { path = "../../../../dev/embedded/embedded-sdmmc-rs" }

# [patch.'https://github.com/gauteh/ahrs-fusion']
# ahrs-fusion = { path = "../../../../dev/embedded/imu/ahrs-fusion" }

# [patch.'https://github.com/gauteh/notecard-rs']
# notecard = { path = "../../../../dev/embedded/notecard-rs" }

# [patch.'https://github.com/gauteh/ambiq-rs']
# ambiq-hal = { path = "../../../../dev/ambiq-rs/ambiq-hal" }

[features]
default = [ "deploy", "storage", "20Hz" ]
continuous = []
20Hz = []
storage = [ "postcard", "embedded-sdmmc" ]
host-tests = []
deploy = [ ]

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-
